### ISSUE TITLE
Add support for reading fish history in `shell_history` table

### ISSUE THREAD

**Issue by alex** [facebook/osquery#1417]
`fish` (http://fishshell.com/) stores its history in `.config/fish/fish_history` as a sort of YAML file with a schema that appears to be:

```yaml
- cmd: <string command>
  when: <integer unix timestamp>
  paths:
    - <string of a path referenced in the command, the paths key is not always present>
```

note that the file didn't actually parse with Python's YAML file, due to what appears to be a quoting issue, so it may not be precisely YAML.

Anyhoo, fish is great, so it'd be cool to have support in osquery.
