### ISSUE TITLE
Snapshot query results flapping

### ISSUE THREAD

**Issue by kliseb** [facebook/osquery#5334]
# Bug report

### What operating system and version are you using?
Various hosts, all on darwin 10.14 but with differing patch and build numbers

### What version of osquery are you using?
`version = 3.3.0`

### What steps did you take to reproduce the issue?
We're using Kolide Launcher and Fleet to monitor our hosts with osquery, and we have seen this issue with multiple different scheduled snapshot queries. One example is with the following query:
```
---
apiVersion: v1
kind: pack
spec:
  name: Verify Compliance Daily
  queries:
    - query: macos_update
      name: macos_update
      interval: 21600
      snapshot: true
      platform: darwin
---
apiVersion: v1
kind: query
spec:
  name: macos_update
  query: select * from plist where path = '/Library/Preferences/com.apple.SoftwareUpdate.plist' and key = 'RecommendedUpdates' and subkey = 'Identifier' and (value like 'Security Update%' or value like 'macOS%');
  platform: darwin
```
There does not seem to be a pattern as to why we will receive an empty snapshot between two non-empty snapshots.

### What did you expect to see?
We expect to see that the snapshot results do not change between runs of the query when a host has not installed a software update.

### What did you see instead?
Occasionally, we will see an empty snapshot between two non-empty snapshots, even though the host has not installed an update. Note on the following that the required update is the same for both non-empty snapshots, so we know that we shouldn't be receiving an empty snapshot in between.
```
{"snapshot":[{"key":"RecommendedUpdates","path":"/Library/Preferences/com.apple.SoftwareUpdate.plist","subkey":"Identifier","value":"Security Update 2018-003"}],"action":"snapshot","name":"pack/Verify Compliance Daily/macos_update","hostIdentifier":"E9337423-46B4-53A9-91C6-19D81C1B8AD9","calendarTime":"Sat Dec 22 15:36:43 2018 UTC","unixTime":1545493003,"epoch":0,"counter":0,"decorations":{"hardware_serial":"XXXXXXXXXXXX","host_uuid":"E9337423-46B4-53A9-91C6-19D81C1B8AD9","hostname":"nicks-macbook-pro.local","username":"nick"}}

{"snapshot":[],"action":"snapshot","name":"pack/Verify Compliance Daily/macos_update","hostIdentifier":"E9337423-46B4-53A9-91C6-19D81C1B8AD9","calendarTime":"Sun Dec 23 13:44:19 2018 UTC","unixTime":1545572659,"epoch":0,"counter":0,"decorations":{"hardware_serial":"XXXXXXXXXXXX","host_uuid":"E9337423-46B4-53A9-91C6-19D81C1B8AD9","hostname":"nicks-macbook-pro.local","username":"nick"}}

{"snapshot":[{"key":"RecommendedUpdates","path":"/Library/Preferences/com.apple.SoftwareUpdate.plist","subkey":"Identifier","value":"Security Update 2018-003"}],"action":"snapshot","name":"pack/Verify Compliance Daily/macos_update","hostIdentifier":"E9337423-46B4-53A9-91C6-19D81C1B8AD9","calendarTime":"Tue Dec 25 22:02:02 2018 UTC","unixTime":1545775322,"epoch":0,"counter":0,"decorations":{"hardware_serial":"XXXXXXXXXXXX","host_uuid":"E9337423-46B4-53A9-91C6-19D81C1B8AD9","hostname":"nicks-macbook-pro.local","username":"nick"}}
```
